# Generated by Django 4.2.11 on 2026-04-11 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePassSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=100)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattlePassTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_req', models.IntegerField()),
                ('reward_name', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('avatar', 'Avatar'), ('theme', 'Theme'), ('badge', 'Badge')], max_length=50)),
                ('reward_value', models.CharField(max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='battlepass.battlepassseason')),
            ],
        ),
    ]
