# Generated by Django 4.2.11 on 2026-04-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlepass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlepasstier',
            options={'ordering': ['season_id', 'level_req', 'pk']},
        ),
        migrations.AlterField(
            model_name='battlepasstier',
            name='reward_value',
            field=models.CharField(help_text='Cheie tehnică (ex. id avatar) sau descriere scurtă.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='owneditem',
            constraint=models.UniqueConstraint(fields=('user', 'item_key'), name='battlepass_owneditem_unique_user_item_key'),
        ),
    ]
