# Generated by Django 4.2.11 on 2026-07-06 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battlepass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepasstier',
            name='reward_type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('theme', 'Temă'), ('badge', 'Insignă')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='owneditem',
            unique_together={('user', 'item_key')},
        ),
    ]
