# Generated by Django 4.2.11 on 2026-04-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battlepass', '0002_alter_battlepasstier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlepassseason',
            options={'ordering': ['-start_date']},
        ),
    ]
