# Generated by Django 4.2.11 on 2026-04-12 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏅', help_text='Emoji afișat ca insignă.', max_length=8)),
                ('trigger', models.CharField(choices=[('first_lesson_quiz', 'Primul quiz la lecție (oricare)'), ('perfect_lesson_quiz', 'Quiz lecție la scor maxim'), ('lesson_quiz_total', 'Număr total quiz-uri lecție'), ('first_legacy_quiz', 'Primul chestionar /quizzes/'), ('legacy_quiz_total', 'Număr chestionare /quizzes/'), ('any_quiz_total', 'Orice quiz-uri (lecții + clasice)'), ('level_at_least', 'Nivel jucător ≥ prag'), ('xp_total', 'XP total ≥ prag'), ('battlepass_claims', 'Recompense Battle Pass revendicate ≥ prag')], max_length=40)),
                ('threshold', models.PositiveIntegerField(default=0, help_text='Pentru numărătoare, nivel minim sau XP: valoarea țintă. Lăsat 0 dacă nu se aplică.')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Realizare',
                'verbose_name_plural': 'Realizări',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Realizare deblocată',
                'verbose_name_plural': 'Realizări deblocate',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='achievements_userachievement_unique_user_achievement'),
        ),
    ]
