# Generated by Django 4.2.11 on 2026-07-08 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user', 'Raport utilizator'), ('server', 'Eroare server')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('new', 'Nou'), ('reviewed', 'Revizuit'), ('resolved', 'Rezolvat')], db_index=True, default='new', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('exception_type', models.CharField(blank=True, max_length=200)),
                ('traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status', 'created_at'], name='feedback_er_kind_bb3b0c_idx')],
            },
        ),
    ]
