# Generated by Django 4.2.11 on 2026-04-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Luminos'), ('dark', 'Întunecat'), ('system', 'La fel ca sistemul')], default='system', max_length=20),
        ),
    ]
