# Generated by Django 4.2.11 on 2026-04-11 11:10

from django.db import migrations, models
import django.db.models.deletion


def copy_quiz_question_links(apps, schema_editor):
    Question = apps.get_model("quizzes", "Question")
    QuizQuestion = apps.get_model("quizzes", "QuizQuestion")
    by_quiz = {}
    for qu in Question.objects.all().order_by("pk"):
        by_quiz.setdefault(qu.quiz_id, []).append(qu)
    for quiz_id, questions in by_quiz.items():
        for order, qu in enumerate(questions):
            QuizQuestion.objects.create(
                quiz_id=quiz_id,
                question_id=qu.id,
                order=order,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quizattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_links",
                        to="quizzes.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_links",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.RunPython(copy_quiz_question_links, noop_reverse),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.AddConstraint(
            model_name="quizquestion",
            constraint=models.UniqueConstraint(
                fields=("quiz", "question"),
                name="quizzes_quizquestion_unique_quiz_question",
            ),
        ),
    ]
