# Generated by Django 4.2.11 on 2026-04-11 16:22

from django.db import migrations, models


def seed_quiz_tags(apps, schema_editor):
    QuizTag = apps.get_model("quizzes", "QuizTag")
    rows = [
        ("clasa-5", "Clasa V", "class", 5),
        ("clasa-6", "Clasa VI", "class", 6),
        ("clasa-7", "Clasa VII", "class", 7),
        ("clasa-8", "Clasa VIII", "class", 8),
        ("clasa-9", "Clasa IX", "class", 9),
        ("clasa-10", "Clasa X", "class", 10),
        ("clasa-11", "Clasa XI", "class", 11),
        ("clasa-12", "Clasa XII", "class", 12),
        ("evaluare-nationala", "Evaluarea Națională", "exam", 1),
        ("bacalaureat", "Bacalaureat", "exam", 2),
    ]
    for slug, name, kind, sort_order in rows:
        QuizTag.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "kind": kind, "sort_order": sort_order},
        )


def unseed_quiz_tags(apps, schema_editor):
    QuizTag = apps.get_model("quizzes", "QuizTag")
    QuizTag.objects.filter(
        slug__in=[
            "clasa-5",
            "clasa-6",
            "clasa-7",
            "clasa-8",
            "clasa-9",
            "clasa-10",
            "clasa-11",
            "clasa-12",
            "evaluare-nationala",
            "bacalaureat",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_question_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('class', 'Clasă'), ('exam', 'Examen')], max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='quizzes.quiztag'),
        ),
        migrations.RunPython(seed_quiz_tags, unseed_quiz_tags),
    ]
