# Generated by Django 4.2.11 on 2026-07-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizattemptanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Ușor'), ('medium', 'Mediu'), ('hard', 'Greu')], max_length=20),
        ),
    ]
