# Generated by Django 4.2.11 on 2026-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_xp',
            field=models.PositiveIntegerField(default=50, help_text='XP maxim la finalizare. XP acordat = acest număr × (scor / scor maxim). 0 = fără XP.'),
        ),
    ]
