# Generated by Django 4.2.11 on 2026-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_options_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='exam_slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
    ]
