# Generated by Django 4.2.11 on 2026-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_chapter_exam_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='class_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='exam_slugs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
