# Generated by Django 4.2.11 on 2026-08-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Grilă'), ('parentheses_drag', 'Plasează parantezele'), ('column_addition', 'Adunare în coloană'), ('column_multiplication', 'Înmulțire în coloană'), ('column_subtraction', 'Scădere în coloană'), ('missing_digits', 'Completează cifrele lipsă'), ('error_spotting', 'Detectează greșeala'), ('parentheses_target', 'Paranteze pentru rezultat-țintă'), ('input_output', 'Mașină intrare–ieșire'), ('factor_builder', 'Construiește factorizarea'), ('factor_error', 'Detectează pasul greșit'), ('factor_match', 'Potrivește forme echivalente')], default='multiple_choice', max_length=30),
        ),
    ]
