# Generated by Django 4.2.11 on 2026-08-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='format_tag',
            field=models.CharField(choices=[('grid', 'Grilă'), ('true_false', 'Adevărat sau fals'), ('interactive', 'Interactiv')], default='grid', max_length=20),
        ),
    ]
