# Generated by Django 4.2.11 on 2026-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_question_format_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Grilă'), ('parentheses_drag', 'Plasează parantezele'), ('column_addition', 'Adunare în coloană'), ('column_multiplication', 'Înmulțire în coloană'), ('column_division', 'Împărțire în coloană'), ('column_subtraction', 'Scădere în coloană'), ('missing_digits', 'Completează cifrele lipsă'), ('error_spotting', 'Detectează greșeala'), ('parentheses_target', 'Paranteze pentru rezultat-țintă'), ('input_output', 'Mașină intrare–ieșire'), ('division_relation', 'Relația împărțirii'), ('operation_chain', 'Lanț de operații'), ('division_table', 'Tabelul împărțirii'), ('numeric_input', 'Răspuns numeric'), ('factor_builder', 'Construiește factorizarea'), ('factor_error', 'Detectează pasul greșit'), ('factor_match', 'Potrivește forme echivalente')], default='multiple_choice', max_length=30),
        ),
    ]
