# Generated by Django 4.2.11 on 2026-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Grilă'), ('parentheses_drag', 'Plasează parantezele'), ('column_addition', 'Adunare în coloană'), ('column_multiplication', 'Înmulțire în coloană'), ('column_division', 'Împărțire în coloană'), ('column_subtraction', 'Scădere în coloană'), ('missing_digits', 'Completează cifrele lipsă'), ('error_spotting', 'Detectează greșeala'), ('parentheses_target', 'Paranteze pentru rezultat-țintă'), ('input_output', 'Mașină intrare–ieșire'), ('division_relation', 'Relația împărțirii'), ('operation_chain', 'Lanț de operații'), ('division_table', 'Tabelul împărțirii'), ('numeric_input', 'Răspuns numeric'), ('factor_builder', 'Construiește factorizarea'), ('factor_error', 'Detectează pasul greșit'), ('factor_match', 'Potrivește forme echivalente'), ('power_builder', 'Construiește sau desfă puterea'), ('power_match', 'Potrivește formele unei puteri'), ('power_table', 'Completează tabelul puterilor'), ('power_cycle', 'Ciclul ultimei cifre'), ('power_square', 'Reprezentarea pătratului'), ('power_rule_chain', 'Lanț de reguli pentru puteri'), ('power_compare', 'Compară două puteri'), ('power_order', 'Ordonează puteri'), ('base_values', 'Completează scrierea într-o bază'), ('base_match', 'Potrivește reprezentări în baze'), ('binary_toggle', 'Construiește numărul binar'), ('base_error', 'Detectează eroarea de conversie'), ('unit_reduction', 'Metoda reducerii la unitate'), ('comparison_method', 'Metoda comparației'), ('operation_sequence', 'Construiește ordinea operațiilor'), ('operation_workbench', 'Calculează expresia pe etape'), ('divisibility_values', 'Completează divizori și multipli'), ('divisibility_select', 'Selectează divizori sau multipli'), ('divisibility_sort', 'Sortează relații de divizibilitate'), ('divisibility_error', 'Detectează eroarea de divizibilitate'), ('criteria_table', 'Tabelul criteriilor de divizibilitate')], default='multiple_choice', max_length=30),
        ),
    ]
