# Generated by Django 4.2.11 on 2026-04-12 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Capitol',
                'verbose_name_plural': 'Capitole',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unic în tot site-ul (folosit în /lectii/&lt;slug&gt;/).', max_length=120, unique=True)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='FoculMatematic.chapter')),
            ],
            options={
                'verbose_name': 'Lecție',
                'verbose_name_plural': 'Lecții',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Clasă',
                'verbose_name_plural': 'Clase',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='FoculMatematic.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Încercare quiz (lecție)',
                'verbose_name_plural': 'Încercări quiz (lecții)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('points', models.PositiveSmallIntegerField(default=10)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='FoculMatematic.lesson')),
            ],
            options={
                'verbose_name': 'Întrebare (lecție)',
                'verbose_name_plural': 'Întrebări (lecții)',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='FoculMatematic.question')),
            ],
            options={
                'verbose_name': 'Variantă',
                'verbose_name_plural': 'Variante',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='FoculMatematic.schoolclass'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='FoculMatematic.quizattempt')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_in_answers', to='FoculMatematic.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_answers', to='FoculMatematic.question')),
            ],
            options={
                'verbose_name': 'Răspuns',
                'verbose_name_plural': 'Răspunsuri',
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('school_class', 'slug'), name='foculmatematic_chapter_unique_slug_per_class'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='foculmatematic_answer_unique_attempt_question'),
        ),
    ]
