# Generated by Django 4.2.11 on 2026-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoculMatematic', '0001_initial_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_max_xp',
            field=models.PositiveIntegerField(default=50, help_text='XP maxim pentru quiz-ul lecției. XP acordat = acest număr × (scor obținut / scor maxim).'),
        ),
    ]
