# Generated by Django 4.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoculMatematic", "0002_add_quiz_xp_fields"),
        ("quizzes", "0005_add_quiz_xp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="quiz_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="Opțional: tag de tip „clasă” din app-ul chestionare; afișează link către lista filtrată.",
                limit_choices_to={"kind": "class"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_classes",
                to="quizzes.quiztag",
                verbose_name="Tag chestionare (clasă)",
            ),
        ),
    ]
